service: banking-api

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 5
  stage: dev
  region: eu-west-1
  environment: '${file(.env.yml):${self:custom.stage}}'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  vpc: '${file(.env.yml):${self:custom.stage}-vpc}'

custom:
  stage: '${opt:stage, self:provider.stage}'

functions:
  ###################################
  # accounts
  ###################################
  accountsList:
    handler: api/accounts.list
    events:
      - http:
          path: api/accounts
          method: get
          cors: true

  accountsGet:
    handler: api/accounts.get
    events:
      - http:
          path: api/accounts/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  ###################################
  # categories
  ###################################
  categoriesList:
    handler: api/categories.list
    events:
      - http:
          path: api/categories
          method: get
          cors: true

  categoriesGet:
    handler: api/categories.get
    events:
      - http:
          path: api/categories/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  ###################################
  # operations
  ###################################
  operationsList:
    handler: api/operations.list
    events:
      - http:
          path: api/operations
          method: get
          cors: true

  operationsGet:
    handler: api/operations.get
    events:
      - http:
          path: api/operations/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  operationsPost:
    handler: api/operations.post
    events:
      - http:
          path: api/operations
          method: post
          cors: true

  operationsPut:
    handler: api/operations.put
    events:
      - http:
          path: api/operations/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true

  operationsPatch:
    handler: api/operations.patch
    events:
      - http:
          path: api/operations/{id}
          method: patch
          cors: true
          request:
            parameters:
              paths:
                id: true

  ###################################
  # statistics
  ###################################
  operations_dailyBalance:
    handler: api/statistics.operations_dailyBalance
    events:
      - http:
          path: api/statistics/operations/dailyBalance
          method: get
          cors: true

  account_dayBalance:
    handler: api/statistics.account_dayBalance
    events:
      - http:
          path: api/statistics/account/dayBalance
          method: get
          cors: true
